### Get all products categories
GET {{base_url}}/manufacturer

### GET product category by id
GET {{base_url}}/manufacturer/1

### POST create a product category
POST {{base_url}}/manufacturer
Content-Type: application/json

{
  "name": "Bombril"
}

### PUT update a product category
PUT {{base_url}}/manufacturer/1
Content-Type: application/json

{
  "name": "Ypê"
}

### DELETE delete a product category
DELETE {{base_url}}/manufacturer/1