### Get all products
GET {{base_url}}/product

### GET product by id
GET {{base_url}}/product/1

### Get by product field name and a name
GET {{base_url}}/product/name?field=ManufacturerName&name=moda

### Get by product price
GET {{base_url}}/product/price?price=19.99

### Get by product price range
GET {{base_url}}/product/priceRange?priceInitial=1&priceFinal=100

### Get by product amount
GET {{base_url}}/product/amount?amount=1

### Get by product amount range
GET {{base_url}}/product/amountRange?amountInitial=1&amountFinal=10

### Get by field and order
GET {{base_url}}/product/order?field=ManufacturerName&direction=desc

### POST create a product
POST {{base_url}}/product
Content-Type: application/json

{
  "name": "Bombril",
  "price": 2.60,
  "manufacturerId" : 1,
  "manufacturingDate" : "2019-07-04",
  "expirationDate" : "2023-07-04",
  "categoryId": 1,
  "amount": 4,
  "stockId": 1
}

### PUT update a product
PUT {{base_url}}/product/1
Content-Type: application/json

{
  "name": "Bombril",
  "price": 2.60,
  "manufacturerId" : 1,
  "manufacturingDate" : "2019-07-04",
  "expirationDate" : "2023-07-04",
  "categoryId": 1,
  "amount": 4,
  "stockId": 1
}
