### Get all products categories
GET {{base_url}}/stock

### Get all products by its name
GET {{base_url}}/stock/name?name=depa

### Get all products by its address
GET {{base_url}}/stock/address?address=Rua

### Get all products by its cep
GET {{base_url}}/stock/cep?cep=60123

### Get by field and order
GET {{base_url}}/stock/order?field=name&direction=asc

### GET product category by id
GET {{base_url}}/stock/1

### POST create a product category
POST {{base_url}}/stock
Content-Type: application/json

{
  "name": "Departamento de produtos de limpeza",
  "address": "Rua Franciliano Freitinha",
  "cep": "60123-132"
}

### PUT update a product category
PUT {{base_url}}/stock/1
Content-Type: application/json

{
  "name": "Depósito",
  "address": "Rua Franciliano Freitinha",
  "cep": "60123-132"
}

### DELETE delete a product category
DELETE {{base_url}}/stock/1